### ISSUE TITLE
Bad argument formatting in dist/index.js

### ISSUE THREAD

**Issue by nwesterhausen** [LoliGothick/clippy-check#40]
```
Run LoliGothick/clippy-check@master
  
Executing cargo fmt (JSON output)
  /home/runner/.cargo/bin/cargo clippy --message=format=json --all-features --
  error: Found argument '--message' which wasn't expected, or isn't valid in this context

    Did you mean '--message-format'?
  
  Usage: cargo check --message-format <FMT>

For more information try '--help'
```  

After a [search](https://github.com/LoliGothick/clippy-check/search?q=format%3Djson), it's formatted correctly in `src/main.ts` but in `dist/index.js` it has the extra `=` character.

Edit: This is probably because I used the reference in readme to us `@master` instead of specifying the tag, I see there was a fix for this but it is not reflected in the main repository.

Edit again: After looking further, seems the PR which fixes that and was released as v0.2.2 did not update `dist/index.js` only the file in `src` so the fix isn't affecting github actions

**Comment by LoliGothick** [comment]
I was unable to work on it due to depression, so I am sorry for the delay, but it has been corrected.
